from __future__ import annotations
import os
from typing import Literal
from mcp.server.apps import Apps, ResourceCsp
WIDGET_URI='ui://widget/sharepoint-upload-inline-v2.html'
BASE_URL=os.getenv('PUBLIC_BASE_URL','https://sharepoint-mcp-hqhfgeauhufbe5cv.francecentral-01.azurewebsites.net').rstrip('/')
apps=Apps()
HTML=f'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{{font-family:Arial;margin:0;padding:16px;background:#f4f6f9}}form{{background:#fff;padding:18px;border-radius:14px}}label{{display:block;margin:10px 0 4px;font-weight:700}}input,select,button{{width:100%;box-sizing:border-box;padding:10px}}button{{margin-top:14px;background:#ee6b23;color:#fff;border:0;border-radius:8px;font-weight:700}}#s{{margin-top:12px;white-space:pre-wrap}}</style></head><body><form id="f"><h2>Upload SharePoint</h2><label>Fichier</label><input type="file" name="file" required><input type="hidden" name="hostname" value="avocarbongroup.sharepoint.com"><label>Site</label><input name="site_path" value="/sites/pdc"><label>Bibliothèque</label><input name="library_name" value="RFQ_Costing Files"><label>Dossier</label><input name="parent_folder_path" value="RFQ Excel"><label>Conflit</label><select name="conflict_behavior"><option value="replace">Remplacer</option><option value="rename">Renommer</option><option value="fail">Annuler</option></select><button type="submit">Envoyer</button><div id="s">Prêt.</div></form><script>const f=document.getElementById("f"),s=document.getElementById("s");f.onsubmit=async e=>{{e.preventDefault();s.textContent="Upload en cours...";try{{const r=await fetch("{BASE_URL}/api/browser-upload",{{method:"POST",body:new FormData(f)}});const p=await r.json();if(!r.ok)throw Error(p.error||("HTTP "+r.status));s.textContent="Upload réussi - "+(p.uploaded_item?.name||"")}}catch(x){{s.textContent="Échec : "+x.message}}}};</script></body></html>'''
@apps.tool(resource_uri=WIDGET_URI,name='open_sharepoint_upload',description='Upload a file to SharePoint directly in ChatGPT.',meta={'ui/resourceUri':WIDGET_URI})
async def open_sharepoint_upload(hostname:str='avocarbongroup.sharepoint.com',site_path:str='/sites/pdc',library_name:str='RFQ_Costing Files',parent_folder_path:str='RFQ Excel',conflict_behavior:Literal['fail','rename','replace']='replace')->dict[str,str]:
    return {'hostname':hostname,'site_path':site_path,'library_name':library_name,'parent_folder_path':parent_folder_path,'conflict_behavior':conflict_behavior}
apps.add_html_resource(WIDGET_URI,HTML,title='AVOCarbon SharePoint Upload',csp=ResourceCsp(connect_domains=[BASE_URL]),prefers_border=True)
